### ISSUE TITLE
List items but not dictionary keys are included when converting Lua tables to JSON

### ISSUE THREAD

**Issue by linkerlin** [xyproto/algernon#109] opened 2022-07-03 07:36 UTC
Algernon REPL:
![image](https://user-images.githubusercontent.com/37062/177030035-ff3a4351-a110-4c7d-8ade-b1931e5afc44.png)

**Comment by xyproto** [comment] 2022-07-03 10:19
Thanks for reporting.

Yes, I guess this should have been converted to a table/dictionary instead. It's not 100% obvious what the result should look like in Lua, though.

In all bug reports, please include these three points:

* Problem description
* Steps to reproduce the issue
* Expected behavior

**Comment by xyproto** [comment] 2022-07-03 10:22
I can reproduce the same behavior, but I get a different result for the second expression

```
lua> json {1,2,3}
[1,2,3]
lua> json {1,2,{}}
ERRO[0014] json: unsupported type: map[interface {}]interface {}

lua> json {1,2,a=100}
[1,2]
lua> json {a=100,1,2}
[1,2]
lua>
```

I guess using a different converter than the built-in json Marshal/Unmarshal feature in Go is needed, for more flexibility.

**Comment by xyproto** [comment] 2022-07-03 10:22
Please add:

* Problem description
* Steps to reproduce the issue
* Expected behavior

**Comment by xyproto** [comment] 2022-07-03 10:55
After #107 was fixed, `json {1,2,3}` and `json {1,2,{}}` works as expected.

**Comment by xyproto** [comment] 2022-07-03 10:56
What is the expected outcome for `json {a=100,1,2}`?

Is it `{100,1,2}` or something like `{a=100,2=1,3=2}`? (since Lua indices count from 1)

**Comment by linkerlin** [comment] 2022-07-04 02:03
> What is the expected outcome for `json {a=100,1,2}`?
> 
> Is it `{100,1,2}`, or something else?
What about json() output:
`{"a":100,"1":1,"2":2}`

**Comment by xyproto** [comment] 2022-07-04 10:12
OK, closing this issue. Please re-open if this should be considered a bug.

**Closed by xyproto** 2022-07-04 10:12 UTC
Labels: bug, waiting-for-a-reply, can-reproduce-the-issue
